// Generated by CoffeeScript 1.7.1
(function() {
  var RippleRpcClient, request;

  request = require('superagent');

  RippleRpcClient = (function() {
    function RippleRpcClient(host) {
      this.host = host;
    }

    RippleRpcClient.prototype.call = function(method, params, callback) {
      return request.post(this.host).send({
        method: method,
        params: [params]
      }).end(function(error, response) {
        if (error) {
          return callback(error);
        } else {
          return callback(null, response.body.result);
        }
      });
    };

    return RippleRpcClient;

  })();

  module.exports = RippleRpcClient;

}).call(this);
